name: Release (Windows portable)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and package
        env:
          # Optional signing (provide CSC_LINK and CSC_KEY_PASSWORD as repo secrets)
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # Enable updater for upstream releases (forks can omit)
          HORIZON_UPDATER_ENABLED: '1'
        run: npm run dist

      - name: List dist contents (debug)
        run: |
          Get-ChildItem -Recurse dist | ForEach-Object { $_.FullName }
        shell: pwsh

      - name: Create GitHub Release and upload portable EXE
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist\**\*.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
